        * exit status 1

 prefix=[C:\Users\umababy.kannan\OneDrive - HCL Technologies Ltd\Documents\Star CAP\platform-infra\live\dev\eu-central-1\platform-datastore]
time=2024-02-06T20:05:48+05:30 level=info msg=╷
│ Error: Invalid index
│
│   on main.tf line 155, in module "platform_dynamodb_table":
│  155:   global_secondary_indexes = local.tables[each.key].global_secondary_indexes
│     ├────────────────
│     │ each.key is "PlatformConfig"
│     │ local.tables is tuple with 21 elements
│
│ The given key does not identify an element in this collection value: a
│ number is required.
╵
╷
│ Error: Invalid index
│
│   on main.tf line 155, in module "platform_dynamodb_table":
│  155:   global_secondary_indexes = local.tables[each.key].global_secondary_indexes
│     ├────────────────
│     │ each.key is "DataIngressLog"
│     │ local.tables is tuple with 21 elements
│
│ The given key does not identify an element in this collection value: a
│ number is required.
╵
╷
│ Error: Invalid index
│
│   on main.tf line 155, in module "platform_dynamodb_table":
│  155:   global_secondary_indexes = local.tables[each.key].global_secondary_indexes
│     ├────────────────
│     │ each.key is "DataAsset"
│     │ local.tables is tuple with 21 elements
│
│ The given key does not identify an element in this collection value: a
│ number is required.
╵
╷
│ Error: Invalid index
│
│   on main.tf line 155, in module "platform_dynamodb_table":
│  155:   global_secondary_indexes = local.tables[each.key].global_secondary_indexes
│     ├────────────────
│     │ each.key is "OrganisationNetworkDetails"
│     │ local.tables is tuple with 21 elements
│
│ The given key does not identify an element in this collection value: a
│ number is required.
╵
╷
│ Error: Invalid index
│
│   on main.tf line 155, in module "platform_dynamodb_table":
│  155:   global_secondary_indexes = local.tables[each.key].global_secondary_indexes
│     ├────────────────
│     │ each.key is "RoleDetails"
│     │ local.tables is tuple with 21 elements
│
│ The given key does not identify an element in this collection value: a
│ number is required.
╵
╷
│ Error: Invalid index
│
│   on main.tf line 155, in module "platform_dynamodb_table":
│  155:   global_secondary_indexes = local.tables[each.key].global_secondary_indexes
│     ├────────────────
│     │ each.key is "UserRoleDetails"
│     │ local.tables is tuple with 21 elements
│
│ The given key does not identify an element in this collection value: a
│ number is required.
╵
╷
│ Error: Invalid index
│
│   on main.tf line 155, in module "platform_dynamodb_table":
│  155:   global_secondary_indexes = local.tables[each.key].global_secondary_indexes
│     ├────────────────
│     │ each.key is "UserTrainingDetails"
│     │ local.tables is tuple with 21 elements
│
│ The given key does not identify an element in this collection value: a
│ number is required.
╵
╷
│ Error: Invalid index
│
│   on main.tf line 155, in module "platform_dynamodb_table":
│  155:   global_secondary_indexes = local.tables[each.key].global_secondary_indexes
│     ├────────────────
│     │ each.key is "UserLoginDetails"
│     │ local.tables is tuple with 21 elements
│
│ The given key does not identify an element in this collection value: a
│ number is required.
╵
╷
│ Error: Invalid index
│
│   on main.tf line 155, in module "platform_dynamodb_table":
│  155:   global_secondary_indexes = local.tables[each.key].global_secondary_indexes
│     ├────────────────
│     │ each.key is "Project"
│     │ local.tables is tuple with 21 elements
│
│ The given key does not identify an element in this collection value: a
│ number is required.
╵
╷
│ Error: Invalid index
│
│   on main.tf line 155, in module "platform_dynamodb_table":
│  155:   global_secondary_indexes = local.tables[each.key].global_secondary_indexes
│     ├────────────────
│     │ each.key is "Audit"
│     │ local.tables is tuple with 21 elements
│
│ The given key does not identify an element in this collection value: a
│ number is required.
╵
╷
│ Error: Invalid index
│
│   on main.tf line 155, in module "platform_dynamodb_table":
│  155:   global_secondary_indexes = local.tables[each.key].global_secondary_indexes
│     ├────────────────
│     │ each.key is "ProjectNetworkDetails"
│     │ local.tables is tuple with 21 elements
│
│ The given key does not identify an element in this collection value: a
│ number is required.
╵
╷
│ Error: Invalid index
│
│   on main.tf line 155, in module "platform_dynamodb_table":
│  155:   global_secondary_indexes = local.tables[each.key].global_secondary_indexes
│     ├────────────────
│     │ each.key is "User"
│     │ local.tables is tuple with 21 elements
│
│ The given key does not identify an element in this collection value: a
│ number is required.
╵
╷
│ Error: Invalid index
│
│   on main.tf line 155, in module "platform_dynamodb_table":
│  155:   global_secondary_indexes = local.tables[each.key].global_secondary_indexes
│     ├────────────────
│     │ each.key is "Instance"
│     │ local.tables is tuple with 21 elements
│
│ The given key does not identify an element in this collection value: a
│ number is required.
╵
╷
│ Error: Invalid index
│
│   on main.tf line 155, in module "platform_dynamodb_table":
│  155:   global_secondary_indexes = local.tables[each.key].global_secondary_indexes
│     ├────────────────
│     │ each.key is "Sites"
│     │ local.tables is tuple with 21 elements
│
│ The given key does not identify an element in this collection value: a
│ number is required.
╵
╷
│ Error: Invalid index
│
│   on main.tf line 155, in module "platform_dynamodb_table":
│  155:   global_secondary_indexes = local.tables[each.key].global_secondary_indexes
│     ├────────────────
│     │ each.key is "DataIngress"
│     │ local.tables is tuple with 21 elements
│
│ The given key does not identify an element in this collection value: a
│ number is required.
╵
╷
│ Error: Invalid index
│
│   on main.tf line 155, in module "platform_dynamodb_table":
│  155:   global_secondary_indexes = local.tables[each.key].global_secondary_indexes
│     ├────────────────
│     │ each.key is "ProjectInfraDetails"
│     │ local.tables is tuple with 21 elements
│
│ The given key does not identify an element in this collection value: a
│ number is required.
╵
╷
│ Error: Invalid index
│
│   on main.tf line 155, in module "platform_dynamodb_table":
│  155:   global_secondary_indexes = local.tables[each.key].global_secondary_indexes
│     ├────────────────
│     │ each.key is "FileUpload"
│     │ local.tables is tuple with 21 elements
│
│ The given key does not identify an element in this collection value: a
│ number is required.
╵
╷
│ Error: Invalid index
│
│   on main.tf line 155, in module "platform_dynamodb_table":
│  155:   global_secondary_indexes = local.tables[each.key].global_secondary_indexes
│     ├────────────────
│     │ each.key is "DataAssetFile"
│     │ local.tables is tuple with 21 elements
│
│ The given key does not identify an element in this collection value: a
│ number is required.
╵
╷
│ Error: Invalid index
│
│   on main.tf line 155, in module "platform_dynamodb_table":
│  155:   global_secondary_indexes = local.tables[each.key].global_secondary_indexes
│     ├────────────────
│     │ each.key is "DataAssetMetadata"
│     │ local.tables is tuple with 21 elements
│
│ The given key does not identify an element in this collection value: a
│ number is required.
╵
╷
│ Error: Invalid index
│
│   on main.tf line 155, in module "platform_dynamodb_table":
│  155:   global_secondary_indexes = local.tables[each.key].global_secondary_indexes
│     ├────────────────
│     │ each.key is "Dataset"
│     │ local.tables is tuple with 21 elements
│
│ The given key does not identify an element in this collection value: a
│ number is required.
╵
╷
│ Error: Invalid index
│
│   on main.tf line 155, in module "platform_dynamodb_table":
│  155:   global_secondary_indexes = local.tables[each.key].global_secondary_indexes
│     ├────────────────
│     │ each.key is "Organisation"
│     │ local.tables is tuple with 21 elements
│
│ The given key does not identify an element in this collection value: a
│ number is required.
╵
time=2024-02-06T20:05:48+05:30 level=error msg=Terraform invocation failed in C:/.terragrunt-cache/XTQi-oi0p63BODQSy4EBJhN-Zak/VlJQvwBldSrlCuJoozEeVg97DMM/platform-datastore prefix=[C:\Users\umababy.kannan\OneDrive - HCL Technologies Ltd\Documents\Star CAP\platform-infra\live\dev\eu-central-1\platform-datastore]

time=2024-02-06T20:05:48+05:30 level=error msg=1 error occurred:
        * exit status 1

