$ python test_postgresdataapi.py
[2023-12-09 19:09:28,171] [test_postgresdataapi] [consolelogger] [setUp:11] [INFO]: "Setting up the test."
[2023-12-09 19:09:28,171] [test_postgresdataapi] [consolelogger] [setUp:13] [INFO]: "Connected to the database."
[2023-12-09 19:09:29,008] [postgresdataapi] [consolelogger] [connect:26] [INFO]: "Connected to the host: adl-com-d1-cdp-dcnexus.cgs723tlzdrk.us-east-1.rds.amazonaws.com, database: postgres"
[2023-12-09 19:09:29,293] [postgresdataapi] [consolelogger] [execute_sql:43] [INFO]: "SQL Statement executed successfully."
[2023-12-09 19:09:29,293] [test_postgresdataapi] [consolelogger] [test_create_table:34] [ERROR]: "Test 'test_create_table' failed. Error: cannot unpack non-iterable NoneType object"
E[2023-12-09 19:09:29,293] [test_postgresdataapi] [consolelogger] [tearDown:20] [INFO]: "Tearing down the test."
[2023-12-09 19:09:29,293] [test_postgresdataapi] [consolelogger] [tearDown:22] [INFO]: "Closed the database connection."
[2023-12-09 19:09:29,293] [test_postgresdataapi] [consolelogger] [setUp:11] [INFO]: "Setting up the test."
[2023-12-09 19:09:29,293] [test_postgresdataapi] [consolelogger] [setUp:13] [INFO]: "Connected to the database."
[2023-12-09 19:09:30,444] [postgresdataapi] [consolelogger] [connect:26] [INFO]: "Connected to the host: adl-com-d1-cdp-dcnexus.cgs723tlzdrk.us-east-1.rds.amazonaws.com, database: postgres"
[2023-12-09 19:09:30,746] [postgresdataapi] [consolelogger] [execute_sql:43] [INFO]: "SQL Statement executed successfully."
[2023-12-09 19:09:30,746] [test_postgresdataapi] [consolelogger] [test_create_table:34] [ERROR]: "Test 'test_create_table' failed. Error: cannot unpack non-iterable NoneType object"
E[2023-12-09 19:09:30,746] [test_postgresdataapi] [consolelogger] [tearDown:20] [INFO]: "Tearing down the test."
[2023-12-09 19:09:30,746] [test_postgresdataapi] [consolelogger] [tearDown:22] [INFO]: "Closed the database connection."
[2023-12-09 19:09:30,746] [test_postgresdataapi] [consolelogger] [setUp:11] [INFO]: "Setting up the test."
[2023-12-09 19:09:30,746] [test_postgresdataapi] [consolelogger] [setUp:13] [INFO]: "Connected to the database."
[2023-12-09 19:09:31,402] [postgresdataapi] [consolelogger] [connect:26] [INFO]: "Connected to the host: adl-com-d1-cdp-dcnexus.cgs723tlzdrk.us-east-1.rds.amazonaws.com, database: postgres"
[2023-12-09 19:09:31,587] [postgresdataapi] [consolelogger] [execute_sql:45] [INFO]: "Error executing SQL statement: relation "test_cicd.non_existent_table" does not exist
LINE 1: SELECT * FROM test_cicd.non_existent_table;
                      ^
"
[2023-12-09 19:09:31,587] [test_postgresdataapi] [consolelogger] [test_table_not_created:56] [ERROR]: "Test 'test_table_not_created' failed. Error: relation "test_cicd.non_existent_table" does not exist
LINE 1: SELECT * FROM test_cicd.non_existent_table;
                      ^
"
E[2023-12-09 19:09:31,587] [test_postgresdataapi] [consolelogger] [tearDown:20] [INFO]: "Tearing down the test."
[2023-12-09 19:09:31,587] [test_postgresdataapi] [consolelogger] [tearDown:22] [INFO]: "Closed the database connection."

======================================================================
ERROR: test_create_table (__main__.TestPostgresDataAPI.test_create_table)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Users\A1086139\git_repo\adl-awsdeploy-cicd\tests\alight\foundation\postgres\test_postgresdataapi.py", line 30, in test_create_table
    query_id, status = self.data_api.execute_sql(sql_statement)
    ^^^^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable NoneType object

======================================================================
ERROR: test_select_from_table (__main__.TestPostgresDataAPI.test_select_from_table)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Users\A1086139\git_repo\adl-awsdeploy-cicd\tests\alight\foundation\postgres\test_postgresdataapi.py", line 38, in test_select_from_table
    self.test_create_table()
  File "D:\Users\A1086139\git_repo\adl-awsdeploy-cicd\tests\alight\foundation\postgres\test_postgresdataapi.py", line 30, in test_create_table
    query_id, status = self.data_api.execute_sql(sql_statement)
    ^^^^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable NoneType object

======================================================================
ERROR: test_table_not_created (__main__.TestPostgresDataAPI.test_table_not_created)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Users\A1086139\git_repo\adl-awsdeploy-cicd\tests\alight\foundation\postgres\test_postgresdataapi.py", line 52, in test_table_not_created
    query_id, status = self.data_api.execute_sql(sql_statement)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\A1086139\git_repo\adl-awsdeploy-cicd\src\alight\foundation\postgres\postgresdataapi.py", line 38, in execute_sql
    self._cursor.execute(sql_statement)
psycopg2.errors.UndefinedTable: relation "test_cicd.non_existent_table" does not exist
LINE 1: SELECT * FROM test_cicd.non_existent_table;
                      ^


----------------------------------------------------------------------
Ran 3 tests in 3.415s

FAILED (errors=3)

A1086139@DESKTOP-899JC7U MINGW64 ~/git_repo/adl-awsdeploy-cicd/tests/alight/foundation/postgres (feature/postgresdeployments)
$
